### ISSUE TITLE
Cache not invalidated properly when changing publicPath

### ISSUE THREAD

**Issue by aldarund** [brunocodutra/webapp-webpack-plugin#105]
I have project with nuxt where i set [publicPath ](https://webpack.js.org/guides/public-path/)during build based on env variable.
``` build: {
     extend: function(config, ctx) {
      if (!ctx.isDev) {
        const awsS3AssetsBucketName = `blabla-${
          process.env.STAGE
        }`
        config.output.publicPath = `https://s3.${
          process.env.AWS_REGION
        }.amazonaws.com/${awsS3AssetsBucketName}/`
      }
 }
 }
```
Even if i change env variable ( so the publicPath changed) webapp-webpack-plugin still output old path until i clean its cache folder.

**Comment by brunocodutra** [comment]
Thanks for reporting.

For the record, the fix is trivial and only requires adding `publicPath` to [the loader's options](https://github.com/brunocodutra/webapp-webpack-plugin/blob/master/src/compiler.js#L20).
