### ISSUE TITLE
 free logo/icon design for webapp-webpack-plugin

### ISSUE THREAD

**Issue by Pelikens** [brunocodutra/webapp-webpack-plugin#122]
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!

**Comment by brunocodutra** [comment]
Absolutely, I'd appreciate it very much!

**Comment by Pelikens** [comment]
Thanks for your reply! That's great! Do you have any special requirements for the logo? Any symbols that should be included? And how do you plan to use the logo? On your web site and etc?

**Comment by brunocodutra** [comment]
No special requirements. 

I'd place it next to the title on the front page [here](https://github.com/brunocodutra/webapp-webpack-plugin#webapp-webpack-plugin), which means it would also appear [here](https://www.npmjs.com/package/webapp-webpack-plugin).

**Comment by Pelikens** [comment]
ok, what name do you want to write? webapp-webpack-plugin?

**Comment by brunocodutra** [comment]
Yeah, but if you think that's too long and might not work well, do you think the initials wwp would be better?

**Comment by Pelikens** [comment]
ok, I'll try both make options. Have a nice day!

**Comment by Pelikens** [comment]
Hi, here is an option for the logo. Please, let me know what do you think? 
![image](https://user-images.githubusercontent.com/39441298/43046079-b2ad895e-8dcc-11e8-945f-c66bcad2c7db.png)

**Comment by brunocodutra** [comment]
Number 1 looks really good! Just a typo `Plagin -> Plugin`.

I feel `plugin` has more emphasis than it should, because the most important word is `webapp` in my opinion. Do you think it would work to slightly increase the font size of `webapp webpack` and similarly decrease the font size of `plugin` just so their widths align with the image in the centre?

**Comment by brunocodutra** [comment]
Actually, since I plan to place it right next to the project title on the front page, do you think just the logo without the text would work?

**Comment by Pelikens** [comment]
it can be so? 
![image](https://user-images.githubusercontent.com/39441298/43046288-41fe7364-8dcf-11e8-8ee3-252dbf4aa397.png)

**Comment by Pelikens** [comment]
![image](https://user-images.githubusercontent.com/39441298/43046327-efccc360-8dcf-11e8-98e0-d24b0bf9d218.png)

**Comment by brunocodutra** [comment]
Excellent, I think Number 3 looks best, would you mind opening a PR?
Just don't forget to correct the spelling ~PLAGIN~ => PLUGIN

**Comment by Pelikens** [comment]
![image](https://user-images.githubusercontent.com/39441298/43046409-144948c0-8dd1-11e8-8a68-ad224f67e90d.png)
 Sorry, English is not my first language, I try not to make mistakes.  I'll open the PR when I make you options of all sizes. color and monochrome, OK?

**Comment by brunocodutra** [comment]
> Sorry, English is not my first language, I try not to make mistakes.

No need to apologise, even native speakers make spelling mistakes :)

>  I'll open the PR when I make you options of all sizes. color and monochrome, OK?

Sounds great, open the PR when you're ready and I'll merge it, thanks again!

**Comment by Pelikens** [comment]
I uploaded all the required files and created a pull-request. Please merge it if everything is Ok
