### ISSUE TITLE
apple-mobile-web-app-status-bar-style

### ISSUE THREAD

**Issue by firsttris** [brunocodutra/webapp-webpack-plugin#124]
Hello,

since the latest iOS update my webapp only shows a white status bar in iOS.

is there an option to create a black status bar instead of black-translucent?

< meta name="apple-mobile-web-app-status-bar-style" content="black" >

regards
Tristan

**Comment by brunocodutra** [comment]
Did you try setting `theme_color` in [`favicons` options](https://github.com/itgalaxy/favicons#usage)?

**Comment by firsttris** [comment]
yes i did try set it to
    favicons: {
      theme_color: "#000", 
    }

but no change
![img_0630](https://user-images.githubusercontent.com/1709260/43287228-a74ea51a-9124-11e8-879d-4f219658e9a6.jpg)

but if i change 
< meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" >
to
< meta name="apple-mobile-web-app-status-bar-style" content="black" >

i get the status bar back.

**Comment by brunocodutra** [comment]
I believe `theme_color` should accept `black-translucent`, have you tried that?

**Comment by firsttris** [comment]
yes

i tried setting it to
black
black-translucent
#000

but my iOS Status Bar is still white.

it will always generate 
< meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" >

but if i change it to
< meta name="apple-mobile-web-app-status-bar-style" content="black" >

i get the status bar back

**Comment by brunocodutra** [comment]
Oh so I got it the other way around, you want it to be `black` but it's always `translucent`.
The reason for that odd behaviour seems to be due to [this line in favicons](https://github.com/itgalaxy/favicons/blob/master/src/config/html.json#L19).
I believe this property should be set to `theme_color` around [this line](https://github.com/itgalaxy/favicons/blob/master/src/helpers.js#L132), but apparently it is not.

I created a follow up ticket against favicons, see itgalaxy/favicons#230

**Comment by uwolfer** [comment]
I've found a plugin which works around this limitation: https://github.com/invalidred/AppleStatusBarStyleWebpackPlugin
Of course, it would be nice if there would be an option in favicons to set this property instead of using another plugin to just do that.

**Comment by firsttris** [comment]
you can also do this with htmlwebpackplugin but then you would have 2 meta tags

**Comment by brunocodutra** [comment]
This feature has shipped with Favicons v5.2
