### ISSUE TITLE
Safari Mask Icon

### ISSUE THREAD

**Issue by colbyfayock** [brunocodutra/webapp-webpack-plugin#127]
Hey! Any intent of supporting Safari mask icons? Happy to put together a PR :)

```
<link rel="mask-icon" href="path/to/favicon.svg" color="#ff00ff">
```

**Comment by brunocodutra** [comment]
I don't see any reason why not, but the feature needs to be added to [`favicons`](https://github.com/itgalaxy/favicons) in order for webapp-webpack-plugin to support it.

**Comment by colbyfayock** [comment]
ah gotcha, okay. ill wander over there. thanks

**Comment by brunocodutra** [comment]
Cool, I'd be happy to review a CR over there.

Colby Fayock <notifications@github.com> schrieb am Mi., 22. Aug. 2018,
14:38:

**Comment by colbyfayock** [comment]
seems like there's a lot of back and forth already about supporting SVG generally. i was going to try to  dig a little first, but is the SVG support that you provide from favicons or are you adding that as an additional layer? sounded like supporting SVG was the only thing holding it back

**Comment by brunocodutra** [comment]
Unless I misunderstood what you are saying, SVG is already supported by
`favicons`, that is the base icon can be a SVG.

Colby Fayock <notifications@github.com> schrieb am Mi., 22. Aug. 2018,
14:50:

**Comment by colbyfayock** [comment]
thats what I was thinking, since you provide the support here, but wonder if it's a different use case. i'll leave a note and see whats up over there

Commented on the previous thread https://github.com/itgalaxy/favicons/issues/126

Thanks
