### ISSUE TITLE
Favicons aren't being included in the html file

### ISSUE THREAD

**Issue by wtchnm** [brunocodutra/webapp-webpack-plugin#141]
Hi! Thanks for your amazing work! 

I already tried to using `inject: 'force'` and using the [v4](https://github.com/brunocodutra/webapp-webpack-plugin/tree/html-webpack-plugin-4) branch, but I keep getting no favicons :(

To reproduce the issue:

- Clone https://github.com/woitechen/tysark.git
- Run `yarn && yarn build`
- Look at `dist/index.html`

**Comment by brunocodutra** [comment]
Thanks for reaching out, could you confirm whether the same configuration works on the latest release with html-webpack-plugin v3?

**Comment by wtchnm** [comment]
Unfortunately it is not working on v3 as well.

**Comment by brunocodutra** [comment]
~Could you share your configuration for `WebappWebpackPlugin`?~

Just realized you shared the repo.

**Comment by brunocodutra** [comment]
@woitechen I believe you have a bug in [this conditional](https://github.com/woitechen/tysark/blob/master/.config/webpack/webpack.prod.js#L214), negating the predicate fixes the issue.

**Comment by wtchnm** [comment]
Hmm, that's right. The issue is with the `speed-measure-webpack-plugin`. Many thanks for your help.
