### ISSUE TITLE
How generete source json stats

### ISSUE THREAD

**Issue by ease-space** [brunocodutra/webapp-webpack-plugin#144]
How to generate a source json stats? I want use in react-helmet)))

**Comment by ease-space** [comment]
My problem is using webapp-webpack-plugin in server side rendering. How inject genereted image in html response server?

**Comment by brunocodutra** [comment]
The built-in feature to generate the json stats file was removed, because I didn't understand the use-case well enough to support it.

Could you elaborate on the options we have? I have no experience in server side rendering.

**Comment by ease-space** [comment]
Hi, I got it. I inject the generated pictures in html with server side rendering. I can make a sample. And you will add me to the library's contributors?))

**Comment by ease-space** [comment]
I want to do a starter kit Server Side Rendering + Code Splliting + Material Ui + React router + Redux Suga + React Helmet + automatig generated favicons. Add link in yuor repositori and make a contributor to your library? Sorry of my English))

**Comment by brunocodutra** [comment]
I'm not sure such a complex example that involves so many other dependencies should belong in this repo, but either way by opening issues [you're a contributor already](https://github.com/brunocodutra/webapp-webpack-plugin#contribution), thanks!
