### ISSUE TITLE
Cache hash should depend on Favicons version

### ISSUE THREAD

**Issue by wclr** [brunocodutra/webapp-webpack-plugin#146]
Is it possible to hash individual files?
The case why: 

There is an issue https://github.com/itgalaxy/favicons/issues/253

With different favicons version, the same source file is processed differently. If we hash only by source file we have a situation with a stale cache on a client.

Or icons-[hash] should also depend on exact favicons version.

**Comment by brunocodutra** [comment]
> Or icons-[hash] should also depend on exact favicons version

That's actually a good point, I think it should indeed.

**Comment by wclr** [comment]
And maybe svg2png or phantomjs =)

**Comment by brunocodutra** [comment]
I'm not sure about these, since they are transitive dependencies that we don't control.

**Comment by brunocodutra** [comment]
I think a compromise we can make to improve the situation is to have [hash] depend on the version of `webapp-webpack-plugin`.
