### ISSUE TITLE
favicon outside of assets folder

### ISSUE THREAD

**Issue by CloudPower97** [brunocodutra/webapp-webpack-plugin#168]
Hello there,
first of all thank you for this great plugin.

I'm trying to use it alongside [`imagemin-webpack`](https://github.com/itgalaxy/imagemin-webpack) but the generated _favicon_ are placed outside of the `assets` folder.
This is unexpected, as shown also [here](https://github.com/brunocodutra/webapp-webpack-plugin/tree/master/test/fixtures/expected/html).

Here is a snippet of my configuration file, if it can help:

```javascript
const ImageminPlugin = require('imagemin-webpack')
const imageminGiflossy = require('imagemin-giflossy')
const imageminMozJpeg = require('imagemin-mozjpeg')
const imageminPngquant = require('imagemin-pngquant')
const imageminSvgo = require('imagemin-svgo')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const WebappWebpackPlugin = require('webapp-webpack-plugin')
```

and in `plugins` array: 

```javascript
[
        new ImageminPlugin({
          bail: false, // Ignore errors on corrupted images
          cache: false,
          imageminOptions: {
            plugins: [
              imageminGiflossy({
                interlaced: true,
                optimizationLevel: 3,
              }),
              imageminMozJpeg({
                quality: 70,
                progressive: true,
              }),
              imageminPngquant({
                speed: 1,
                quality: [0.85, 1], //lossy settings
                optimizationLevel: 5,
                strip: true,
              }),
              imageminSvgo({
                removeViewBox: true,
              }),
            ],
          },
        }),
        new HtmlWebpackPlugin(),
        new WebappWebpackPlugin({
          logo: './public/favicon.png',
          // This is going to create a custom manifest.json
          // Refer to this documentation for more information : https://github.com/itgalaxy/favicons#usage
          favicons: {
            appName: 'React Advanced Boilerplate - PostCSS support, i18next and much more',
            appShortName: 'React Advanced Boilerplate',
            theme_color: '#0d47a1',
            lang: 'it-IT',
            start_url: './',
          },
        }),
]
```

Any help is much appreciated.

Thank you in advance and keep up the good work!

**Comment by brunocodutra** [comment]
I'm glad it's useful to you!

Does it work as expected if you remove `ImageminPlugin` from the `plugins` array?

**Comment by CloudPower97** [comment]
Yes, indeed, it does work without a problem.

Any suggestions?

**Comment by brunocodutra** [comment]
I wonder if placing `webapp-webpack-plugin` _before_ `imagemin-webpack` helps?

**Comment by CloudPower97** [comment]
Nope, unfortunately this does not fix the problem. :(

**Comment by brunocodutra** [comment]
I inspected their code and it does some weird business with assets paths, but I couldn't find anything wrong. Have you considered [skipping the favicons generated in `assets/`](https://github.com/itgalaxy/imagemin-webpack#plugin-options)?

If you intentionally set up `imagemin-webpack` to minify favicons, have you checked whether it actually makes any noticeable difference?

**Comment by CloudPower97** [comment]
Hey @brunocodutra, it seems I got this working with
```javascript
include: /.*\/src\/assets/,
```

I already tried `exclude` and `filter` previously, maybe I was just doing something wrong.

Anyway, thank you for your help! :smile:

**Comment by brunocodutra** [comment]
Glad it works for you!
