### ISSUE TITLE
Update favicons dependency to v5.4.0

### ISSUE THREAD

**Issue by synedra-mpe** [brunocodutra/webapp-webpack-plugin#178]
Favicons module has been update with many important changes, we are waiting for since Nov 2018.

https://github.com/itgalaxy/favicons/releases/tag/v5.4.0

**Comment by brunocodutra** [comment]
Thanks for the heads-up, v5.4.0 was shipped with a regression (see itgalaxy/favicons#268), as soon as v5.4.1is out (see itgalaxy/favicons#271) I'll update this plugin.

**Comment by synedra-mpe** [comment]
bump

**Comment by synedra-mpe** [comment]
bump

**Comment by brunocodutra** [comment]
v2.7.1 is out #183!
