### ISSUE TITLE
How to specify Manifest-Metadata?

### ISSUE THREAD

**Issue by scrayos** [brunocodutra/webapp-webpack-plugin#28]
I'd like to manually specify the name, short-name, start URL, theme color, background-color, orientation, etc. How can this be achieved? The documentation within the readme only offers "some" information, and doesn't even mention "background-color" for example.

It is important however, that those options aren't only set/configurable for manifest.json, but also for the related entries like:
```html
<meta name="msapplication-TileColor" content="#fff">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="#fff">
```

Aside from that: Excellent idea and project! Keep up the great work!

**Comment by brunocodutra** [comment]
Perfect timing! I'm about to merge some changes to the README that, among other things, make it more explicit where detailed documentation about metadata configuration can be found. You can [have a look at the current draft here](https://github.com/brunocodutra/webapp-webpack-plugin/blob/readme/README.md#advanced-usage). I'd love to hear some feedback, specially if you think there's still room for improvement.

In short, you can refer to [favicons documentation](https://github.com/evilebottnawi/favicons#usage) for all the available configuration options, which I reproduce below for convenience:

```.js
new WebappWebpackPlugin({
 
  ...

  favicons: {
    appName: null,                  // Your application's name. `string`
    appDescription: null,           // Your application's description. `string`
    developerName: null,            // Your (or your developer's) name. `string`
    developerURL: null,             // Your (or your developer's) URL. `string`
    background: "#fff",             // Background colour for flattened icons. `string`
    theme_color: "#fff",            // Theme color for browser chrome. `string`
    path: "/",                      // Path for overriding default icons path. `string`
    display: "standalone",          // Android display: "browser" or "standalone". `string`
    orientation: "portrait",        // Android orientation: "portrait" or "landscape". `string`
    start_url: "/?homescreen=1",    // Android start application's URL. `string`
    version: "1.0",                 // Your application's version number. `number`
    logging: false,                 // Print logs to console? `boolean`
    online: false,                  // Use RealFaviconGenerator to create favicons? `boolean`
    preferOnline: false,            // Use offline generation, if online generation has failed. `boolean`
    icons: {
        // Platform Options:
        // - offset - offset in percentage
        // - shadow - drop shadow for Android icons, available online only
        // - background:
        //   * false - use default
        //   * true - force use default, e.g. set background for Android icons
        //   * color - set background for the specified icons
        //
        android: true,              // Create Android homescreen icon. `boolean` or `{ offset, background, shadow }`
        appleIcon: true,            // Create Apple touch icons. `boolean` or `{ offset, background }`
        appleStartup: true,         // Create Apple startup images. `boolean` or `{ offset, background }`
        coast: { offset: 25 },      // Create Opera Coast icon with offset 25%. `boolean` or `{ offset, background }`
        favicons: true,             // Create regular favicons. `boolean`
        firefox: true,              // Create Firefox OS icons. `boolean` or `{ offset, background }`
        windows: true,              // Create Windows 8 tile icons. `boolean` or `{ background }`
        yandex: true                // Create Yandex browser icon. `boolean` or `{ background }`
    }
  }

  ...

})
```

**Comment by scrayos** [comment]
Wow, that was a fast response!

Looks fantastic to me. There was a little notice (as a comment) in the previous version, that mentioned favicons' usage instructions, but it wasn't clear enough to me.

The "For example"-part is especially useful, in my opinion, because it shows how "configuration = {}" translates to "favicons: {}" in the configuration. That part was, what I was most uncertain about. I asked myself, if those are separate options, or if they're all grouped under "favicons".

A slight improvement I'd still like to have outlined a little more is the relationship between your plugin and "favicons". A little sentence like "The options specified under the 'favicons'-directive are directly handed over to [favicons](https://github.com/evilebottnawi/favicons#usage)." should do. Because that's what I didn't get at first.

Thank you very much for your kind support, aswell as providing this excellent resource :+1:

**Comment by brunocodutra** [comment]
> The "For example"-part is especially useful, in my opinion, because it shows how "configuration = {}" translates to "favicons: {}" in the configuration. That part was, what I was most uncertain about. I asked myself, if those are separate options, or if they're all grouped under "favicons".

That's really helpful, thanks for the feedback!
