### ISSUE TITLE
Plugin causes non-deterministic builds, [chunkhash] is different

### ISSUE THREAD

**Issue by wbobeirne** [brunocodutra/webapp-webpack-plugin#69]
Using `webpack@4.5.0`, adding `webapp-webpack-plugin` to my build causes me to get a different chunkhash each build, even when they're identical in content. I'm also finding this to be true with `favicons-webpack-plugin`, so I think this is something Webpack has changed about the way it calculates the hash. However, maybe there's something that can be changed about the way the plugin works to fix this.

**Comment by wbobeirne** [comment]
After some tinkering, I've determined that this is from the caching. Setting `cacheDirectory: false` fixes this issue.

**Comment by brunocodutra** [comment]
I would never have guessed, thanks for looking into this!

To be honest I'm unsure what the correct behaviour here would be, but from what you have gathered, if there is a bug it's likely to be in [`cache-loader`](https://github.com/webpack-contrib/cache-loader), which we use under the hood to provide caching.

In any case can't you just use `[hash]` instead? As of v2.0.1 the hash is generated from the input icon along with the metadata provided under the `favicons` configuration key, so it remains constant across builds, as long as neither of those change.

**Comment by brunocodutra** [comment]
@wbobeirne Any updates?

**Comment by brunocodutra** [comment]
I'll close this due to lack of activity, feel free to reopen if needed.
