### ISSUE TITLE
Support for webpack 4?

### ISSUE THREAD

**Issue by jpaas** [brunocodutra/webapp-webpack-plugin#9]
This plugin no longer works with Webpack 4. Any plans to update?

**Comment by brunocodutra** [comment]
I plan to work on that this weekend.

**Comment by jpaas** [comment]
That would be much appreciated. Thank-you @brunocodutra !

**Comment by brunocodutra** [comment]
@jpaas [v1.1](https://www.npmjs.com/package/webapp-webpack-plugin) should support Webpack 4. 

Do let me know if it works for you once you get the chance to give it a spin.

**Comment by jpaas** [comment]
@brunocodutra it works perfectly! Thank-you
