### ISSUE TITLE
Webpack 4 support?

### ISSUE THREAD

**Issue by aldarund** [brunocodutra/webapp-webpack-plugin#91]
Im trying to use it with nuxt ( edge) which is uses webpack 4. And while the plugin triggered and the code here executes fine
https://github.com/brunocodutra/webapp-webpack-plugin/blob/master/src/index.js#L53
the resulting page doesnt contain any favicon code that was added here.
Original plugin works fine and favicon html exist, except a error with double tap -> https://github.com/jantimon/favicons-webpack-plugin/issues/126#issuecomment-393507904

So as i understand a bit different api should be used for webpack 4 like in original plugin?

**Comment by brunocodutra** [comment]
I'm not sure what could be going wrong, if that line is executed it means we are delivering the modified HTML back to html-webpack-plugin, could you share an example that reproduces the issue?

Also, how did you verify that line is in fact executed?

> So as i understand a bit different api should be used for webpack 4 like in original plugin?

I'm not sure I understand what you mean by _different api_, are you referring to the user facing configuration? 

I should clarify that despite the fact this plugin was originally forked from favicons-webpack-plugin, it has since then completely diverged from it in virtually every way.

**Comment by aldarund** [comment]
>Also, how did you verify that line is in fact executed?

I have added some logging.

>I'm not sure I understand what you mean by different api, are you referring to the user facing configuration?

Im not familiar with webpack api, initially i though that your code not using tapAsync but now i see that i was wrong. So disregard this part.


I have found problem. That code executed 2 times by webpack. And one time 
htmlPluginData.plugin.options.inject is false. Other time is with true.
First is with index.ssr.html  (for ssr), second with index.spa.html ( for spa). 
So it doesnt add headers with ssr for that reason. If i just comment that check all works fine.

**Comment by brunocodutra** [comment]
The value of `htmlPluginData.plugin.options.inject` reflects the `inject` flag of [`html-webpack-plugin` configuration](https://github.com/jantimon/html-webpack-plugin#options), which is supposed to disable HTML injection when set to `false`.

I'm not familiar with nuxt, but do you have control over the configuration of `html-webpack-plugin` to make sure it's not set to `false`?

**Comment by aldarund** [comment]
no, i dont have any control
here is relevant code from nuxt
https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/client.js#L36

**Comment by aldarund** [comment]
Maybe add something like forceInject option to plugin that will inject even if htmlPluginData.plugin.options.inject is false ?
If thats fine i can create a pr.

**Comment by brunocodutra** [comment]
How about overloading the existing [`inject`](https://github.com/brunocodutra/webapp-webpack-plugin#advanced-usage) flag, such that it may be

* `false` to disable html injection regardless of html-webpack-plugin configuration
* `true` to enable html injection provided injection is enabled in html-webpack-plugin configuration
* `force` to enable html injection regardless of html-webpack-plugin configuration

The default value would remain `true`.

Would you be interested in creating a PR for that?

**Comment by aldarund** [comment]
Ye, sounds better than my suggestion :)  I will create pr.
