### ISSUE TITLE
find-cache-dir

### ISSUE THREAD

**Issue by alecmev** [brunocodutra/webapp-webpack-plugin#96]
Consider using [`find-cache-dir`](https://github.com/avajs/find-cache-dir) to locate the default cache directory. This is what [`babel-loader` and `eslint-loader` are already doing](https://github.com/avajs/find-cache-dir#adopters), so it shouldn't surprise the user. I'm personally interested in this because I don't like unnecessary configuration (changing plugin options), `.gitignore` / `.eslintignore` / `.prettierignore` / `.dockerignore` / `.*ignore` bloat, and longer directory listings.

One thing to look out for is that `yarn` wipes out `node_modules/.cache` on every install, [apparently](https://github.com/avajs/find-cache-dir/issues/1#issuecomment-342427717), but no big deal, this is just a cache.

**Comment by brunocodutra** [comment]
Sounds like a great idea, thanks for the heads up!
